### PR TITLE
HSIEO-5499: IPM classes renaming

### PR DESCRIPTION
**Pull request by Beiming-Zhang**
Rename existing classes in IPM package based on proposal
[Copy of zpm_to_ipm_rename (version 2).xlsx](https://github.com/intersystems-community/zpm/files/7941914/Copy.of.zpm_to_ipm_rename.version.2.xlsx)
:

### CODE REVIEW

**Comment by Beiming-Zhang** [comment]
@daimor  Branch updated with the fix; would you plz re-run the Action workflow?

**Comment by Beiming-Zhang** [comment]
@daimor  Hey Dmitry, we just updated the branch with a fix. Looks like the CI Action pipelines finished successfully.

**Comment by daimor** [comment]
@Beiming-Zhang, btw, if you did not know, CI produces an XML installer for every build.
Can be found in artifacts section of the latest build
https://github.com/intersystems-community/zpm/actions/runs/1761186706

**Comment by daimor** [comment]
Looks like running tests not working at all. It just skips it.
And GitHub actions execute tests with the verbose flag, but the output is just very empty.
In CI, it's `Test and Verify` section

could you check it?

**Comment by Beiming-Zhang** [comment]
@daimor  Is it ok to give me the permission to run actions? Some parts of the verification are difficult to test locally

**Comment by evshvarov** [comment]
@Beiming-Zhang! I provided you the access, please accept it

**Pull request merged**
