### PR TITLE
deployed modules support

### PR DESCRIPTION
**Pull request by daimor**
Support for deployed modules.
--
Example of module.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Export generator="Cache" version="25">
<Document name="demo.ZPM">
<Module>
 <Name>demo</Name>
  <Version>1.0.0</Version>
  <Description>DEMO.</Description>
  <Keywords>demo</Keywords>
  <SourcesRoot>src</SourcesRoot>
  <Resource Name="Sample.Demo.PKG" Deploy="true"/>
</Module>
</Document>
</Export>
```

Load module, will be loaded in the developer mode my default with the command `load`
```
zpm "load /path/to/module"
```

package as tgz file
```
zpm "package demo"
```
or publish it to registry 
```
zpm "publish demo"
```

Then install tgz file or from that registry, in a new place
```
zpm "install /path/to/demo-1.0.0.tgz"
zpm "install demo"
```

### CODE REVIEW

**Comment by daimor** [comment]
Yes, sure, this is very important. And I would think of it as a next step, and that should be done together with support form registry.

**Comment by isc-tleavitt** [comment]
https://github.com/intersystems-community/zpm/pull/120 may be helpful for this

**Comment by daimor** [comment]
> #120 may be helpful for this

Yeah, this is a good place. And multi-version support on registry. So, we can directly request build for particular version of IRIS

**Comment by isc-tleavitt** [comment]
Information on the current platform version needs to be pushed into search criteria sent to the registry (of course).

To be clear - I'm a HUGE fan of this feature and have wanted to see it for a while. :)

**Comment by isc-tleavitt** [comment]
For the initial scope, I think module.xml in the .tgz only (not in source) should have SystemRequirements generated based on the platform version used for packaging.

**Comment by daimor** [comment]
> For the initial scope, I think module.xml in the .tgz only (not in source) should have SystemRequirements generated based on the platform version used for packaging.

Agree

**Comment by daimor** [comment]
So, added support on Registry too. And It will check the version of IRIS during installation
At the moment, check only major and minor e.g. 2022.2, in hope it should be enough in most cases. Not sure that  we have to be too strict

**Comment by isc-tleavitt** [comment]
I think checking major + minor is enough.

**Pull request merged**
