### PR TITLE
Deployment Enabled

### PR DESCRIPTION
**Pull request by nsolov**
Added multiple remote registry support

`-publish 1`  required in repo command to enable publishing into the registry

`repo -r -n registry -url https://your-registry.com -publish 1`

### CODE REVIEW

**Comment by isc-tleavitt** [comment]
As it stands this doesn't allow multiple servers, it allows two, one with deployment enabled and one not.
DeploymentEnabled should be allowed to be 1 or null instead of 1 or 0 - the unique index will allow one server with it set to 1 (as intended), and many with it set to null.

**Comment by daimor** [comment]
> As it stands this doesn't allow multiple registries, it allows two, one with deployment enabled and one not. DeploymentEnabled should be allowed to be 1 or null instead of 1 or 0 - the unique index will allow one server with it set to 1 (as intended), and many with it set to null.

look here, if 0 it makes it null, so, it's ok
```
Method %OnBeforeSave(insert As %Boolean) As %Status [ Private, ServerOnly = 1 ]
{
	// Leave DeploymentEnabled null to make unique index work right
	// (i.e., deployment can only be enabled for one remote server.)
	Set:..DeploymentEnabled=0 ..DeploymentEnabled=""
	Quit $$$OK
}
```

**Comment by isc-tleavitt** [comment]
> > As it stands this doesn't allow multiple registries, it allows two, one with deployment enabled and one not. DeploymentEnabled should be allowed to be 1 or null instead of 1 or 0 - the unique index will allow one server with it set to 1 (as intended), and many with it set to null.
> 
> look here, if 0 it makes it null, so, it's ok
> 
> ```
> Method %OnBeforeSave(insert As %Boolean) As %Status [ Private, ServerOnly = 1 ]
> {
> 	// Leave DeploymentEnabled null to make unique index work right
> 	// (i.e., deployment can only be enabled for one remote server.)
> 	Set:..DeploymentEnabled=0 ..DeploymentEnabled=""
> 	Quit $$$OK
> }
> ```

Ah - didn't realize we already had code for that, great!

**Comment by daimor** [comment]
Well, I've decided to change some logic a bit. I don't want to force users to use publish flag, WWE already have two ways of authorizations on registry, which means that the server with that settings may be used for publishing.  So, I've ordered the list of configured registries in order

- Server with DeploymentEnabled = 1
- Server with Token 
- Server with Username and Password
- Any other servers
So, `publish 1` just raise thee priority

Updated the login on changing settings by repo command, so, already defined properties may be limited, as well as the type of registry
```
zpm "repo -n registry -publish 1"
zpm "repo -n registry -token sometoken"
zpm "repo -n registry -username demo -password demo"
```

**Review by daimor — APPROVED** [review]

**Pull request merged**
